### ISSUE TITLE
Some of the properties for resources need to be Nilable

### ISSUE THREAD

**Issue by marghidanu** [jgaskins/kubernetes#1]
I've started playing with this library to develop a K8s operator but bumped into a few issues. I had to adjust by hand a few properties in the Pod resources for this to work; I suspect it might be the case for other resources as well.

```crystal
field generate_name : String?
```

also 

```
field block_owner_deletion : Bool?
```

**Comment by jgaskins** [comment]
I haven’t noticed this before when fetching `Pod`s from the k8s API, but I went ahead and made them nilable. One of the hard parts about porting these data structures to Crystal is having to go through all the places these resources are defined in the K8s code and figuring out which ones are marked with `omitempty` and either setting defaults or making them nilable. In a few places I’ve set defaults (like strings to empty, booleans to `false`, numbers to `0`, etc) but I’m still figuring out how some of these properties are used outside of K8s itself.

Also since I rarely use more than a few properties from any resource I’ve mostly only added things that either _seem_ useful or that I’ve actually used. If there’s a way to export a CRD-style spec for some of these resources we could just use `Kubernetes.import_crd` to load them.

A lot of this shard is still trial and error, but it does work for operators I’ve been building:

- NATS (`StatefulSet`, `Service`, `PersistentVolumeClaim`)
- Postgres (`StatefulSet`, `Service`, `PersistentVolumeClaim`)
- Redis (`StatefulSet`, `Service`, `PersistentVolumeClaim`)
- Heroku-style App operator (`Certificate`, `Ingress`, `Service`, `Deployment`, `Job`)
